[package]
name = "match-example"
version = "0.1.0"
authors = ["TAKAHASHI Tomohiro <takahashi.tomohiro@classmethod.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
