[package]
name = "associated-type"
version = "0.1.0"
authors = ["Yoshihito Hirakawa <hirakawa.yoshihito@classmethod.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
